#ifndef WYTR_YARC_GPIO_H
#define WYTR_YARC_GPIO_H

//MAX6675
#define THERMOCOUPLE_DATA_OUT_PIN 26
#define THERMOCOUPLE_CHIP_SELECT_PIN 27
#define THERMOCOUPLE_CLOCK_PIN 14
#define THERMOCOUPLE_VCC_PIN 12

#define SOLID_STATE_RELAY_OUTPUT_PIN 33

#define BUZZER_PIN 32
#define BUZZER_CHANNEL 1

#endif